public enum GameEvent
{
    NONE = 0,

    LEVEL_COMPLETED = 200,
    LEVEL_FAILED = 201,
    LEVEL_EXTRA_MOVE_REJECTED = 205,
    LEVEL_STARTED = 202,

    // Entity Events
    ENTITY_SELECTED = 300,
    ENTITY_DESELECTED = 301,
    ENTITY_DESTROYED = 302,
    ENTITY_SPAWNED = 303,
    ENTITY_ANIMATION_STATE_CHANGED = 304,
    ENTITY_MISSION_STATE_CHANGED = 305,
    ENTITY_MOVED = 306,
    ENTITY_ATTACKED = 307,
    ENTITY_DAMAGED = 308,
    ENTITY_STOPPED = 309,
}
